<a href="https://colab.research.google.com/github/Amitkumar631/Nttc-project/blob/master/ntcc_image_similarity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import random
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
from tensorflow.keras.datasets import mnist

from keras.models import Sequential
from keras.layers import Conv2D, ZeroPadding2D, Activation, Input, concatenate, Dropout, GlobalAveragePooling2D
from keras.models import Model
from keras.layers.pooling import MaxPooling2D
from keras.layers.merge import Concatenate
from keras.layers.core import Lambda, Flatten, Dense
from keras.initializers import glorot_uniform
from sklearn.preprocessing import LabelBinarizer
from keras.optimizers import *
from keras.engine.topology import Layer
from keras import backend as K
from keras.regularizers import l2
from keras.utils.vis_utils import plot_model
import os
from PIL import Image

In [ ]:
train_path='/content/drive/MyDrive/Covid19-dataset/train'
folders=os.listdir(train_path)
print(folders)

['Covid', 'Pneumonia', 'Normal']


In [ ]:
test_path='/content/drive/MyDrive/Covid19-dataset/test'

In [ ]:
from keras.preprocessing import image
image_data=[]
covid_image_data=[]
normal_image_data=[]
pneumonia_image_data=[]
covid_labels=[]
normal_labels=[]
pneumonia_labels=[]
labels=[]
for ix in folders:
  path=os.path.join(train_path+'/',ix)
  for im in os.listdir(path):
    img=image.load_img(os.path.join(path+'/',im),target_size=((224,224)))
    img_array=image.img_to_array(img)
    if(ix=='Covid'):
      image_data.append(img_array)
      labels.append(2)
    elif (ix=='Normal'):
      image_data.append(img_array)
      labels.append(0)
    else:
      image_data.append(img_array)
      labels.append(1)

In [ ]:
combined=list(zip(image_data,labels))
#random.shuffle(combined)
image_data[:],labels[:]=zip(*combined)
print(labels[:5])

[2, 2, 2, 2, 2]


In [ ]:
X_train=np.array(image_data)
Y_train=np.array(labels)
print(X_train.shape, Y_train.shape)

(259, 224, 224, 3) (259,)


In [ ]:
from keras.preprocessing import image
covid_image_data=[]
normal_image_data=[]
pneumonia_image_data=[]
covid_labels=[]
normal_labels=[]
pneumonia_labels=[]
image_data=[]
labels=[]
for ix in folders:
  path=os.path.join(test_path+'/',ix)
  for im in os.listdir(path):
    img=image.load_img(os.path.join(path+'/',im),target_size=((224,224)))
    img_array=image.img_to_array(img)
    if(ix=='Covid'):
     # covid_image_data.append(img_array)
      #covid_labels.append(2)
      image_data.append(img_array)
      labels.append(2)
    elif (ix=='Normal'):
     # normal_image_data.append(img_array)
      #normal_labels.append(0)
      image_data.append(img_array)
      labels.append(0)
    else:
     # pneumonia_image_data.append(img_array)
      #pneumonia_labels.append(1)
      image_data.append(img_array)
      labels.append(1)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
combined=list(zip(image_data,labels))
#random.shuffle(combined)
image_data[:],labels[:]=zip(*combined)
print(labels[:5])

[2, 2, 2, 2, 2]


In [ ]:
X_test=np.array(image_data)
Y_test=np.array(labels)
print(X_test.shape, Y_test.shape)

(66, 224, 224, 3) (66,)


In [ ]:
from keras.utils import np_utils
X_train=X_train/255.0
X_test=X_test/255.0
Y_train = np_utils.to_categorical(Y_train, 3)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras import layers,models
num_classes = 3

model = Sequential([
    layers.Conv2D(16,3, padding = "same", activation = "relu"),
    layers.MaxPooling2D(),
    layers.Conv2D(32,3, padding = "same", activation = "relu"),
    layers.MaxPooling2D(),
    layers.Conv2D(48,3,padding='same',activation='relu'),
    layers.MaxPooling2D(),
    layers.Flatten(),
    layers.Dense(128,activation = "relu"),
    layers.Dense(num_classes,activation='softmax')
])

In [ ]:
model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])


In [ ]:
model.fit(X_train,Y_train,batch_size=8,epochs=10)

Epoch 1/10
33/33 [==============================] - 13s 366ms/step - loss: 0.7395 - accuracy: 0.7297
Epoch 2/10
33/33 [==============================] - 12s 364ms/step - loss: 0.2950 - accuracy: 0.8880
Epoch 3/10
33/33 [==============================] - 12s 369ms/step - loss: 0.0831 - accuracy: 0.9691
Epoch 4/10
33/33 [==============================] - 12s 374ms/step - loss: 0.0288 - accuracy: 0.9923
Epoch 5/10
33/33 [==============================] - 12s 368ms/step - loss: 0.0531 - accuracy: 0.9768
Epoch 6/10
33/33 [==============================] - 12s 369ms/step - loss: 0.1081 - accuracy: 0.9653
Epoch 7/10
33/33 [==============================] - 12s 373ms/step - loss: 0.0154 - accuracy: 0.9961
Epoch 8/10
33/33 [==============================] - 12s 373ms/step - loss: 0.0014 - accuracy: 1.0000
Epoch 9/10
33/33 [==============================] - 12s 373ms/step - loss: 3.7704e-04 - accuracy: 1.0000
Epoch 10/10
33/33 [==============================] - 12s 370ms/step - loss: 2.0787e-04 

In [ ]:
YY_test=Y_test
YY_test=np_utils.to_categorical(YY_test,3)
#YY_test=np_utils.to_categorical(YY_test,3)

In [ ]:
model.evaluate(X_test,YY_test)

3/3 [==============================] - 1s 211ms/step - loss: 0.3627 - accuracy: 0.9242


[0.36265888810157776, 0.9242424368858337]

In [ ]:
y_pred=model.predict(X_test)
y_pred

array([[4.80408602e-09, 1.26582878e-08, 1.00000000e+00],
       [1.51142228e-06, 6.42857867e-06, 9.99992013e-01],
       [3.74491445e-11, 1.64209951e-06, 9.99998331e-01],
       [3.40328654e-10, 2.88411650e-09, 1.00000000e+00],
       [1.03297043e-06, 3.26344502e-06, 9.99995708e-01],
       [1.19200072e-08, 6.89502656e-02, 9.31049705e-01],
       [4.13226462e-06, 2.76084453e-08, 9.99995828e-01],
       [2.28551856e-12, 1.21202259e-09, 1.00000000e+00],
       [4.74839089e-06, 4.48345199e-05, 9.99950409e-01],
       [1.55385127e-08, 1.96955854e-10, 1.00000000e+00],
       [5.31458155e-10, 1.03357670e-04, 9.99896646e-01],
       [1.04926086e-08, 6.95959868e-09, 1.00000000e+00],
       [7.22894677e-09, 4.11840340e-09, 1.00000000e+00],
       [2.16774099e-11, 4.69099369e-12, 1.00000000e+00],
       [5.79588892e-08, 1.47004528e-06, 9.99998450e-01],
       [5.80508475e-10, 2.15333401e-07, 9.99999762e-01],
       [5.60446779e-07, 7.10885274e-07, 9.99998689e-01],
       [2.74904073e-06, 3.47026

In [ ]:
print(labels[0:26])

[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]


In [ ]:
print(labels[26:46])

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [ ]:
covid_fvector=y_pred[0:26,:]
covid_fvector

array([[4.80408602e-09, 1.26582878e-08, 1.00000000e+00],
       [1.51142228e-06, 6.42857867e-06, 9.99992013e-01],
       [3.74491445e-11, 1.64209951e-06, 9.99998331e-01],
       [3.40328654e-10, 2.88411650e-09, 1.00000000e+00],
       [1.03297043e-06, 3.26344502e-06, 9.99995708e-01],
       [1.19200072e-08, 6.89502656e-02, 9.31049705e-01],
       [4.13226462e-06, 2.76084453e-08, 9.99995828e-01],
       [2.28551856e-12, 1.21202259e-09, 1.00000000e+00],
       [4.74839089e-06, 4.48345199e-05, 9.99950409e-01],
       [1.55385127e-08, 1.96955854e-10, 1.00000000e+00],
       [5.31458155e-10, 1.03357670e-04, 9.99896646e-01],
       [1.04926086e-08, 6.95959868e-09, 1.00000000e+00],
       [7.22894677e-09, 4.11840340e-09, 1.00000000e+00],
       [2.16774099e-11, 4.69099369e-12, 1.00000000e+00],
       [5.79588892e-08, 1.47004528e-06, 9.99998450e-01],
       [5.80508475e-10, 2.15333401e-07, 9.99999762e-01],
       [5.60446779e-07, 7.10885274e-07, 9.99998689e-01],
       [2.74904073e-06, 3.47026

In [ ]:
covid_fvector.shape

(26, 3)

In [ ]:
pneumonia_fvector=y_pred[26:46,:]
pneumonia_fvector

array([[4.0778810e-01, 4.1183919e-01, 1.8037277e-01],
       [1.3623786e-03, 9.9863762e-01, 7.1932334e-12],
       [1.1596786e-02, 9.8814338e-01, 2.5990646e-04],
       [7.5502917e-02, 9.2449504e-01, 2.1335909e-06],
       [2.1136281e-01, 7.8863549e-01, 1.7093889e-06],
       [1.2717526e-01, 6.1738253e-01, 2.5544223e-01],
       [5.0337583e-02, 9.4942915e-01, 2.3328139e-04],
       [4.2303255e-01, 5.7688373e-01, 8.3711762e-05],
       [1.4941685e-03, 9.9850583e-01, 6.9179856e-10],
       [1.4862620e-09, 1.0000000e+00, 2.9081768e-14],
       [1.3398120e-07, 9.9999988e-01, 5.4091513e-13],
       [2.2143668e-03, 9.9777502e-01, 1.0577625e-05],
       [5.3337019e-02, 1.5259166e-01, 7.9407138e-01],
       [1.3473965e-04, 9.9986506e-01, 2.5239927e-07],
       [1.2599631e-05, 9.9998677e-01, 5.4600542e-07],
       [9.8418266e-02, 9.0158176e-01, 1.5250979e-08],
       [8.9521887e-04, 9.9909997e-01, 4.9413788e-06],
       [3.1164088e-06, 9.9979013e-01, 2.0676773e-04],
       [5.5454964e-11, 1.000

In [ ]:
pneumonia_fvector.shape

(20, 3)

In [ ]:
normal_fvector=y_pred[46:,:]
normal_fvector

array([[9.9999964e-01, 3.3207590e-07, 6.9873818e-09],
       [9.9141932e-01, 8.5806325e-03, 7.7937643e-14],
       [9.7634107e-01, 2.3658907e-02, 6.3320846e-09],
       [9.9987018e-01, 1.2790387e-04, 1.8752712e-06],
       [9.9981517e-01, 1.8481858e-04, 2.1272411e-11],
       [9.9978405e-01, 2.1596672e-04, 2.8783957e-08],
       [9.2623043e-01, 7.3769502e-02, 4.3926043e-08],
       [9.9779838e-01, 2.2015455e-03, 4.8895252e-13],
       [9.9951410e-01, 4.8563365e-04, 2.4205337e-07],
       [3.6011699e-03, 9.9639755e-01, 1.2540233e-06],
       [8.8981539e-01, 1.1018462e-01, 9.2970115e-10],
       [9.9856251e-01, 1.4374487e-03, 1.1967236e-12],
       [4.1030575e-02, 9.5896941e-01, 3.0930699e-12],
       [1.2536868e-03, 9.8773557e-01, 1.1010824e-02],
       [2.4595646e-02, 9.7540432e-01, 2.0563062e-09],
       [9.9006420e-01, 9.9357944e-03, 2.2709695e-08],
       [9.9999368e-01, 6.3593930e-06, 9.8050923e-10],
       [9.9345011e-01, 6.5499772e-03, 2.4428286e-09],
       [9.9906701e-01, 9.330

In [ ]:
from scipy import spatial
from sklearn.metrics.pairwise import cosine_similarity
from scipy import sparse
covid_fvector_sparse,normal_fvector_sparse=sparse.csr_matrix(covid_fvector),sparse.csr_matrix(normal_fvector)
sim_sparse=cosine_similarity(covid_fvector_sparse,normal_fvector_sparse,dense_output=False)
print(sim_sparse)

  (0, 19)	0.00035515393
  (0, 18)	4.8335047e-09
  (0, 17)	7.346319e-09
  (0, 16)	5.784682e-09
  (0, 15)	2.7867314e-08
  (0, 14)	1.4882854e-08
  (0, 13)	0.011146854
  (0, 12)	1.2855299e-08
  (0, 11)	4.823501e-09
  (0, 10)	7.360155e-09
  (0, 9)	1.2712245e-06
  (0, 8)	2.4698124e-07
  (0, 7)	4.8324935e-09
  (0, 6)	5.3068735e-08
  (0, 5)	3.359699e-08
  (0, 4)	4.827702e-09
  (0, 3)	1.8803204e-06
  (0, 2)	1.1592947e-08
  (0, 1)	4.9135367e-09
  (0, 0)	1.17914745e-08
  (1, 19)	0.00035666348
  (1, 18)	1.517455e-06
  (1, 17)	1.5562445e-06
  (1, 16)	1.5124558e-06
  (1, 15)	1.5988059e-06
  :	:
  (24, 4)	1.4929215e-07
  (24, 3)	2.024775e-06
  (24, 2)	1.6019737e-07
  (24, 1)	1.508461e-07
  (24, 0)	1.5622382e-07
  (25, 19)	0.00035528076
  (25, 18)	1.3165594e-07
  (25, 17)	1.3416755e-07
  (25, 16)	1.3260693e-07
  (25, 15)	1.5468585e-07
  (25, 14)	1.8348217e-08
  (25, 13)	0.011146854
  (25, 12)	1.854486e-08
  (25, 11)	1.3164598e-07
  (25, 10)	1.3325412e-07
  (25, 9)	1.2719514e-06
  (25, 8)	3.738036e-07


In [ ]:
#similarity between covid and pneumonia
from scipy import spatial
from sklearn.metrics.pairwise import cosine_similarity
from scipy import sparse
covid_fvector_sparse,pneumonia_fvector_sparse=sparse.csr_matrix(covid_fvector),sparse.csr_matrix(pneumonia_fvector)
sim_sparse=cosine_similarity(covid_fvector_sparse,pneumonia_fvector_sparse,dense_output=False)
print(sim_sparse)

  (0, 19)	2.0957248e-08
  (0, 18)	1.26583135e-08
  (0, 17)	0.00020682378
  (0, 16)	4.9584905e-06
  (0, 15)	2.9920766e-08
  (0, 14)	5.58671e-07
  (0, 13)	2.650923e-07
  (0, 12)	0.97990316
  (0, 11)	1.0613856e-05
  (0, 10)	1.26588295e-08
  (0, 9)	1.2658317e-08
  (0, 8)	1.3358296e-08
  (0, 7)	0.00011703221
  (0, 6)	0.00024537527
  (0, 5)	0.37557504
  (0, 4)	2.107109e-06
  (0, 3)	2.3131938e-06
  (0, 2)	0.00026301964
  (0, 1)	1.2672032e-08
  (0, 0)	0.29715934
  (1, 19)	6.4369297e-06
  (1, 18)	6.42863e-06
  (1, 17)	0.00021323975
  (1, 16)	1.137581e-05
  (1, 15)	6.5714985e-06
  :	:
  (24, 4)	2.3125413e-06
  (24, 3)	2.4983462e-06
  (24, 2)	0.00026319528
  (24, 1)	1.8684204e-07
  (24, 0)	0.29715958
  (25, 19)	2.1225826e-08
  (25, 18)	1.2926848e-08
  (25, 17)	0.00020682404
  (25, 16)	4.958873e-06
  (25, 15)	4.3950102e-08
  (25, 14)	5.589411e-07
  (25, 13)	2.653779e-07
  (25, 12)	0.97990316
  (25, 11)	1.0614405e-05
  (25, 10)	1.2927381e-08
  (25, 9)	1.2926852e-08
  (25, 8)	1.3816607e-08
  (25, 7)

In [ ]:
#similarity between normal and pneumonia
from scipy import spatial
from sklearn.metrics.pairwise import cosine_similarity
from scipy import sparse
normal_fvector_sparse,pneumonia_fvector_sparse=sparse.csr_matrix(normal_fvector),sparse.csr_matrix(pneumonia_fvector)
sim_sparse=cosine_similarity(normal_fvector_sparse,pneumonia_fvector_sparse,dense_output=False)
print(sim_sparse)

  (0, 19)	6.6934354e-07
  (0, 18)	3.3213146e-07
  (0, 17)	3.4491404e-06
  (0, 16)	0.000896357
  (0, 15)	0.10851745
  (0, 14)	1.2931873e-05
  (0, 13)	0.00013508991
  (0, 12)	0.06581923
  (0, 11)	0.0022196313
  (0, 10)	4.6605723e-07
  (0, 9)	3.3356227e-07
  (0, 8)	0.0014967349
  (0, 7)	0.5913498
  (0, 6)	0.052944757
  (0, 5)	0.18698524
  (0, 4)	0.25887486
  (0, 3)	0.08139868
  (0, 2)	0.011735458
  (0, 1)	0.0013645681
  (0, 0)	0.6718202
  (1, 19)	0.00865491
  (1, 18)	0.008654573
  (1, 17)	0.00865769
  (1, 16)	0.00955056
  (1, 15)	0.117116526
  :	:
  (18, 4)	0.25977647
  (18, 3)	0.082329124
  (18, 2)	0.012668962
  (18, 1)	0.002298141
  (18, 0)	0.67245334
  (19, 19)	0.00045609186
  (19, 18)	0.00045575466
  (19, 17)	0.0004589451
  (19, 16)	0.0013517808
  (19, 15)	0.108970165
  (19, 14)	0.0004683546
  (19, 13)	0.0005905125
  (19, 12)	0.06625298
  (19, 11)	0.002675056
  (19, 10)	0.0004558886
  (19, 9)	0.0004557561
  (19, 8)	0.0019521567
  (19, 7)	0.591717
  (19, 6)	0.053399615
  (19, 5)	0.1875